s = "AACGACCAAACTTAACGACCCAGGAACGACCAACGACCCAACGACCCAACGACCATAACGACCAACGACCGAAACGACCTAAACGACCAACGACCACGTGACATAACGACCCCCTCGAACGACCCATTCGGGAACGACCAACGACCAACGACCTTAACGACCGCTATGAAACGACCCAACGACCAGAACGACCGAACGACCGGAACGACCTCGCCAAAACGACCGATCGTCGTAACGACCGGAACGACCAGGAACGACCCTTACGAACGACCGGGAACGACCTAACGACCATAACGACCAACGACCAAACGACCTAACGACCGCTAACGACCTAAACGACCGTAACGACCAACGACCGAACGACCAGAACGACCAAGGTCTGTAAACGACCAACGACCAACGACCAAAAACGACCATGCAACGACCCATGAAACGACCGTATAACGACCGAACGACCACGTGTACCAACGACCTAACGACCACTGGCAACGACCCAACGACCCTTAACGACCGTGAACGACCCTAACGACCTAACGACCAACGACCAACGACCAACGCGCTAACGACCAATGTAACGACCTAACGACCGCAACGACCCAACGACCAAAACGACCTGAACGACCAACGACCCAAACGACCCTAACGACCAACGACCAATTCCCAACGACCACCGTAACGACCAACGACCAACGACCAACGACCGAACGACCTAACGACCCAACGACCGTAACGACCGAACGACCCTCCATCAAACGACCCGAACGACCGGAACGACCAACGACCAACGACCCCTGATCAACGACCAACGACCGCAACGACCCCAGGAACGACCAACGACCAACGACC"
t = "AACGACCAA"
matches = []
match = s.find(t)+1
matches.append(match)
while len(s) >= len(t) and matches[-1] != 0:
    s = s[int(match):]
    if s.find(t)+1 != 0:
        match = s.find(t)+1
        matches.append(match+matches[-1])
results = " ".join(str(m) for m in matches)
print(results)
